default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 2003601234
  host: 127.0.0.1 # або інша адреса вашого сервера PostgreSQL, якщо потрібно
  timeout: 5000

development:
  <<: *default
  database: askme_development

test:
  <<: *default
  database: askme_test

production:
  <<: *default
  database: askme_production
  username: askme
  password: <%= ENV['ASKME_DATABASE_PASSWORD'] %>
